class_name GodotMsg


enum {
	GODOT_READY, 
	GODOT_FOREGROUND, 
	NEW_VEHICLE_SNAPSHOT, 
	NEW_ENERGY_SNAPSHOT, 
	ENERGY_SITE_COMPONENT_SELECTED, 
	LOG, 
	VEHICLE_MARKERS_RESPONSE, 
	MOVE_CAMERA_RESPONSE, 
	FIRST_PRODUCT_LOADED, 
	FPS_LOG_RECEIVED, 
}

const Name = {
	GODOT_READY: "GODOT_READY", 
	GODOT_FOREGROUND: "GODOT_FOREGROUND", 
	NEW_VEHICLE_SNAPSHOT: "NEW_VEHICLE_SNAPSHOT", 
	NEW_ENERGY_SNAPSHOT: "NEW_ENERGY_SNAPSHOT", 
	ENERGY_SITE_COMPONENT_SELECTED: "ENERGY_SITE_COMPONENT_SELECTED", 
	LOG: "LOG", 
	VEHICLE_MARKERS_RESPONSE: "VEHICLE_MARKERS_RESPONSE", 
	MOVE_CAMERA_RESPONSE: "MOVE_CAMERA_RESPONSE", 
	FIRST_PRODUCT_LOADED: "FIRST_PRODUCT_LOADED", 
	FPS_LOG_RECEIVED: "FPS_LOG_RECEIVED", 
}
