shader_type canvas_item;
render_mode blend_premul_alpha;

uniform vec4 background_color : hint_color = vec4(0.9,0.9,0.9,1.0);
uniform vec4 road_color : hint_color = vec4(0.8,0.8,0.8,1.0);

// streaming textures from autopilot
uniform sampler2D bev_dense : hint_white;
uniform sampler2D bev_type : hint_white;
uniform sampler2D bev_line_flow : hint_black;
uniform sampler2D bev_crosswalk : hint_black;
uniform float u_clamp_prediction = 1.0;
uniform vec2 bev_size = vec2(225.);
uniform float flip_angle = 0;

// texture generated by skin.gd based on current skin file
uniform sampler2D edge_color_lut : hint_albedo;

// try to normalize a pair of 100% saturated pixels 
// ie the concept is roughly  .. [255,255] > [128, 128]
//                       and  .. [255,0]   > [255,0]

float normalized_sample(sampler2D image, vec2 uv, vec2 sample_buffer_resolution, vec2 heading_angle)
{
	vec2 pixel_size = 1.f / sample_buffer_resolution;
	vec2 sample_pos = uv;

    // Make the magnitude of the angle 1 pixel
	vec2 heading_offset = heading_angle * vec2(pixel_size);

    // 3 samples: current, left, right
    float s1 = texture(image, sample_pos).r;
    float s2 = texture(image, sample_pos + heading_offset * 1.).r;
    float s3 = texture(image, sample_pos - heading_offset * 1.).r;
	
	// total (plus small epsilon to avoid divide by zero)
	float st = (s1+s2+s3)+0.00001; 
	
	// fudge factor for target saturation based on max of sampled pixels 
	float m = max(s1, s2);
	m = max(m, s3);
	m = smoothstep(0., 0.4, m);
	
	float x = m/st;
	
	// tiny padding from extra samples
	float o = s1 + (s2*.02) + (s3*.02);
	
	// ensure we don't completely flatten s1. multiply by 15% for a small saturation bump
	return min(1.0, max(s1*0.33, o*x*1.15));
}


float sample(sampler2D t, vec2 uv)
{	
	float s1 =   texture(bev_line_flow, uv).r; // 1-255 = 0-180 deg; 0=invalid
	float flow =  s1;
	
	const float one_bit = 0.00392; // (1.0 / 255.0)
	
	// subtract the invalid 0 bit; scale out range
	flow -=  one_bit;
	flow = max(0.0, flow);
	flow /= (one_bit*180.0); // scale to 180 deg as 0 .. 1 range
	
	flow = mix(flow, 0.0-flow, flip_angle); // flip rotation 
	flow *= (3.141592); // convert to radians

	// default to x heading is s1 == invalid
	vec2 heading = mix(vec2(1.0, 0.0),  vec2(sin(flow), cos(flow)), step(0.001, s1));
	return normalized_sample(t, uv, bev_size, heading);

}

float edge_sample(vec2 uv)
{
	const float generalMax = 0.65;
	float s = texture(bev_dense, uv).r;
	return s / generalMax;
}

float square_blur_road_edge(vec2 uv)
{
	const float stepSize = 1.0; // sub-pixel offset

	// 3x3 gaussian weights (for corner, side and center):
	const float w00 = 0.07;
	const float w01 = 0.12;
	const float w11 = 0.19;

	vec2 dx = vec2( stepSize / bev_size.x, 0.0 );
	vec2 dy = vec2( 0.0, stepSize / bev_size.y );

	float s00 = w00 * edge_sample( uv - dx - dy );
	float s01 = w01 * edge_sample( uv      - dy );
	float s02 = w00 * edge_sample( uv + dx - dy );

	float s10 = w01 * edge_sample( uv - dx      );
	float s11 = w11 * edge_sample( uv           );
	float s12 = w01 * edge_sample( uv + dx      );

	float s20 = w00 * edge_sample( uv - dx + dy );
	float s21 = w01 * edge_sample( uv      + dy );
	float s22 = w00 * edge_sample( uv + dx + dy );

	float row0 = s00 + s01 + s02;
	float row1 = s10 + s11 + s12;
	float row2 = s20 + s21 + s22;

	float total = (row0 + row1 + row2);
	total = min(1.0, total);
	return total;
}


void fragment()
{ 
	// Sharpen the lines and store that:
	//float pred = sample(bev_dense, UV); // oriented blur
	//float pred = texture(bev_dense, UV).r; // straight sample
	//float pred = edge_sample(UV); // biased simple
	float pred = square_blur_road_edge(UV); // gaussian blur

	vec4 line_color = vec4(1.0, 1.0, 1.0, pred);
	COLOR = line_color;
}