shader_type canvas_item;
render_mode blend_premul_alpha;

uniform vec4 background_color : hint_color = vec4(0.9,0.9,0.9,1.0);
uniform vec4 road_color : hint_color = vec4(0.8,0.8,0.8,1.0);

// streaming textures from autopilot
uniform sampler2D bev_dense : hint_white;
uniform sampler2D bev_type : hint_white;
uniform vec2 bev_size = vec2(225.);

// texture generated by skin.gd based on current skin file
uniform sampler2D edge_color_lut : hint_albedo;

float blur5(sampler2D image, vec2 uv, vec2 resolution, vec2 direction) {
  float color = 0.0;
  vec2 off1 = vec2(1.3333333333333333) * direction;
  color += texture(image, uv).r * 0.29411764705882354;
  color += texture(image, uv + (off1 / resolution)).r * 0.35294117647058826;
  color += texture(image, uv - (off1 / resolution)).r * 0.35294117647058826;
  return color; 
}

float sample(sampler2D t, vec2 uv)
{
	return blur5(t, uv, bev_size, vec2(0.66, 0.0));
}

void fragment()
{ 
	COLOR = vec4(background_color.rgb,0.0);
	float pred = sample(bev_dense, UV);

	// Lines
	float line_type = texture(bev_type, UV).r + 0.002;
	vec4 line_color = (texture(edge_color_lut, vec2(line_type, 0.5)));

	pred *= line_color.a;

	COLOR = vec4(mix(COLOR.rgb, line_color.rgb,  step(0.05,pred)), max(pred,COLOR.a));
}
